### PR TITLE
CI: disable routable check for vmware

### PR DESCRIPTION
**Pull request by Itxaka**
There seems to be a race condition that can cause terraform to
timeout while checking if an IP is routable. Disable this check for
the moment.

Related to: https://github.com/SUSE/avant-garde/issues/1682

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by pablochacin** [comment]
I think that this change is dangerous in the context of machines with multiple network interfaces, as some may not be routable. See [comment in this terraform issue](https://github.com/hashicorp/terraform-provider-vsphere/issues/446#issuecomment-377792483)

**Comment by Itxaka** [comment]
I do agree on this @pablochacin but this should be only a temp fix while the issue is fixed upstream, even if the issue is this!

As for the moment we dont expect to have multiple network interfaces on machine provision(which is the only place this should hit) I felt that it was ok to tempfix this.

I will report this upstream tomorrow and try to find if the issue its actually that so we can start moving the real fix along.

**Comment by pablochacin** [comment]
> I do agree on this @pablochacin but this should be only a temp fix while the issue is fixed upstream, even if the issue is this!
The problem is that we deliver these templates to customers. So we should find a way to override this setting only for the CI.

**Comment by pablochacin** [comment]
My suggestion is to make this behavior dependent on a variable we can override in the CI but by default, will behaveas today.

**Comment by Itxaka** [comment]
@pablochacin @jordimassaguerpla @davidcassany updated as mentioned on the meeting.

Tested introducing the change on existing deployed infra and no changes were triggered, so it should be 100% safe to introduce as it has no effect on customers at all unless they want to change this value.

`Plan: 0 to add, 0 to change, 0 to destroy.`

**Pull request merged**
