### PR TITLE
Show cluster status on each node

### PR DESCRIPTION
**Pull request by suseclee**
## Why is this PR needed?

we need a command that allows to show a global overview of the cluster status.
Therefore, we extend "skuba cluster status" to give node status.

Fixes #

The sample outputs:
```
skuba cluster status
** This is an UNTAGGED version and NOT intended for production usage. **
NAME       STATUS    ROLE     OS-IMAGE                              KERNEL-VERSION           KUBELET-VERSION   CONTAINER-RUNTIME   HAS-UPDATES   HAS-DISRUPTIVE-UPDATES   CAASP-RELEASE-VERSION
master-0   Ready     master   SUSE Linux Enterprise Server 15 SP1   4.12.14-197.29-default   v1.16.2           cri-o://1.16.1      no            no                       <none>
worker-0   NotReady  <none>   SUSE Linux Enterprise Server 15 SP1   4.12.14-197.29-default   v1.16.2           cri-o://1.16.1      no            no                       <none>

skuba cluster status
** This is an UNTAGGED version and NOT intended for production usage. **
NAME       STATUS   ROLE     OS-IMAGE                              KERNEL-VERSION           KUBELET-VERSION   CONTAINER-RUNTIME   HAS-UPDATES   HAS-DISRUPTIVE-UPDATES   CAASP-RELEASE-VERSION
master-0   Ready    master   SUSE Linux Enterprise Server 15 SP1   4.12.14-197.29-default   v1.16.2           cri-o://1.16.1      no            no                       <none>
worker-0   Ready    <none>   SUSE Linux Enterprise Server 15 SP1   4.12.14-197.29-default   v1.16.2           cri-o://1.16.1      no            no                       <none>

skuba cluster status
** This is an UNTAGGED version and NOT intended for production usage. **
NAME       STATUS                      ROLE     OS-IMAGE                              KERNEL-VERSION           KUBELET-VERSION   CONTAINER-RUNTIME   HAS-UPDATES   HAS-DISRUPTIVE-UPDATES   CAASP-RELEASE-VERSION
master-0   Ready                       master   SUSE Linux Enterprise Server 15 SP1   4.12.14-197.29-default   v1.16.2           cri-o://1.16.1      no            no                       <none>
worker-0   Ready,SchedulingDisabled    <none>   SUSE Linux Enterprise Server 15 SP1   4.12.14-197.29-default   v1.16.2           cri-o://1.16.1      no            no                       <none>
```

## Anything else a reviewer needs to know?

The status of  `skuba cluster status` matches status of `kubectl get nodes`.
After kubectl cordon worker-1, SchedullingDisabled was added in status.

kubectl get nodes
NAME       STATUS                     ROLES    AGE   VERSION
master-0   Ready                      master   46m   v1.16.2
worker-0   Ready                      <none>   42m   v1.16.2
worker-1   Ready,SchedulingDisabled   <none>   35m   v1.16.2

## Info for QA

When skuba does init or join, the status will be NotReady immediately. But after 1-2 min, the node will be Ready status.

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by jodavis-suse** [comment]
LGTM

**Comment by jodavis-suse** [comment]
I hate to slow this down, but I think this change should also be included in the README.md where it gives the example of `kubectl caasp cluster status`.

**Comment by jodavis-suse** [comment]
As this already merged, will include an update in a revision to https://github.com/SUSE/skuba/pull/938

**Comment by suseclee** [comment]
> As this already merged, will include an update in a revision to #938

Thanks. I thought I will create it for another Doc card. because I am not familiar with `kubectl caasp cluster status`. But it is great for you to update it. Thanks Jo.

**Comment by jodavis-suse** [comment]
AFAIK, `kubectl caasp cluster status` is just a link to the skuba command, so I used the output from my local test as a guide to update the README.md

**Comment by jenting** [comment]
I think we missed a PR to https://github.com/SUSE/doc-caasp.

**Comment by jodavis-suse** [comment]
hmm, interesting. I just searched the Administration guide and it does not mention 'skuba cluster status' or 'kubectl caasp cluster status' anywhere.  

The Deployment guide at https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#cluster.bootstrap and the Quickstart https://documentation.suse.com/suse-caasp/4.1/single-html/caasp-quickstart/#cluster.bootstrap do have an example `cluster status` output, so we should create a Doc issue for updating that with both STATUS and ROLE.

**Comment by jodavis-suse** [comment]
Created https://github.com/SUSE/doc-caasp/issues/696 to track the Docs update.  I think that will address Jenting's comment.

**Pull request merged**
