### PR TITLE
update suggestions for port versions go from 422 to 500 (#1833)

### PR DESCRIPTION
**Pull request by cclhsu**
update suggestions for port versions go from 422 to 500 (#1833)

Signed-off-by: cclhsu <clark.hsu@suse.com>

## Why is this PR needed?

update suggestions for port versions go from 422 to 500 (#1833)

Fixes # https://github.com/SUSE/avant-garde/issues/1833

## What does this PR do?

We found that the versions.go are not in sync between 4.2.2 and 5.0.0.
This is because the release-caasp-4.2.2 and release-caasp.5.0.0 were branched at the same time. We need now to port the changes from versions.go that were introduced in 4.2.2 to 5.0.0.

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by jenting** [comment]
BTW, will we have a branch name `release-caasp-4.2.2`?

**Comment by jenting** [comment]
Isn't all the container image at v5 starting back from rev1?

**Comment by jordimassaguerpla** [comment]
> Isn't all the container image at v5 starting back from rev1?

This is to be in sync with k8s 1.17 (caasp 4.2.2).

V5 is k8s 1.18.

**Comment by jordimassaguerpla** [comment]
Unit tests are failing but I can't understand why
https://ci.suse.de/blue/organizations/jenkins/caasp-jobs%2Fpr%2Ftest/detail/PR-1274/1/pipeline

**Comment by jordimassaguerpla** [comment]
They fail because we need https://github.com/SUSE/skuba/pull/1265/files

**Comment by jordimassaguerpla** [comment]
I just rebased it.

**Pull request merged**
