### PR TITLE
Disable firewall in vmware+libvirt load balancers (SUSE/avant-garde#1337)

### PR DESCRIPTION
**Pull request by Itxaka**
We moved the firewalld service to be managed by skuba, but
unfortunately on libvirt and vmware the LB is a machine itself
and skuba doesnt run anything on there, so the firewalld service
could still be enabled and running

This patch disables firewalld on cloud-init for vmware and
libvirt

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes https://github.com/SUSE/avant-garde/issues/1337

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by Itxaka** [comment]
> This was done in purpose, please have a look at: #927, skuba is taking care of this, so we untangle how infra is deployed from the skuba deployment.

How is that posible if you cant reach the LB from the deployer node because the firewall is up? We cant even bootstrap a node properly (hint, on kubelet start it tries to reach the apiserver but it cant becuase the firewall on the lb is blocking the calls)

The only reason this seems to work on openstack its because the openstack images do not come with firewalld anymore. On vmware it never worked (basically because we are not bootstrapping a cluster in that job, its a fake job that does nothing)

So either skuba its not doing it properly or there is an extra issue here. Let me have a deeper look at this

**Comment by Itxaka** [comment]
> Normally we have this disabled by default in the images, which image do you use ?

@lcavajani default one used by CI, `SLES15-SP1-GM-up190905-guestinfo`

**Comment by ereslibre** [comment]
Hm, that's certainly interesting. We are using SSH to connect to the new machine, and at the first stages we are disabling `firewalld` using `skuba`, so as long as `firewalld` allows connections on the 22 port (that I believe it should), there should not be any problem... am I missing something?

**Comment by Itxaka** [comment]
> Hm, that's certainly interesting. We are using SSH to connect to the new machine, and at the first stages we are disabling firewalld using skuba, so as long as firewalld allows connections on the 22 port (that I believe it should), there should not be any problem... am I missing something?

We are both missing something I think.

Skuba runs on the master.

Load balancer is a different machine.

Ergo its impossible for skuba to disable the firewalld in the LB if it runs against the master. 

:laughing: :laughing:

**Comment by ereslibre** [comment]
Maybe we can perform this at the `lb.tpl`, since it's specific to the LB then.

**Comment by Itxaka** [comment]
> so it means we also need to re-enable this for libvirt as well

Yep!

> Maybe we can perform this at the lb.tpl, since it's specific to the LB then.

Agreed!

**Pull request merged**
