### PR TITLE
Remove hyperkube migration

### PR DESCRIPTION
**Pull request by evrardjp**
Without this patch, hyperkube will be migrated from 1.17.4 to
1.17.x, which is not something we want.

This is a re-implementation for backport reasons of the
patch https://github.com/SUSE/skuba/pull/1293.

## Why is this PR needed?

This prevents us for releasing a caasp v4.2+ (below 4.5) that would migrate away from hyperkube.

Partial-Fix https://github.com/SUSE/avant-garde/issues/1859

## What does this PR do?

Remove hyperkube migration, which is only required in the skuba master/v5/v4.5 branch.

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by evrardjp** [comment]
skuba-test shouldn't fail with this patch. The error is unrelated.

**Comment by evrardjp** [comment]
Rebased.

**Comment by evrardjp** [comment]
@Klaven rebased.

**Comment by evrardjp** [comment]
I am not sure why this wasn't merged before renaming the branch, but someone should tackle this backport, else we'll be in real trouble soon.

**Comment by jordimassaguerpla** [comment]
@evrardjp Could you please reopen this PR against maintenance-caasp-v4.2 branch? Thanks

**Pull request closed without merging**
