### PR TITLE
Update terraform files for tf 0.12

### PR DESCRIPTION
**Pull request by evrardjp**
These are the automatic and manual operations to perform for a terraform 0.12
upgrade.

I have tested terraform OpenStack end-to-end, including a skuba run, and a
terraform destroy.

I have done the upgrade and eventual validation fixes for libvirt and vmware.
I didn't run the deploy on those.

AWS is failing on my local machine, as I don't have the provider necessary
for the upgrade.

### CODE REVIEW

**Comment by bergmannf** [comment]
It seems they readded the `template_file` resource - the first PR for migration had to remove those blocks #774 

However running:

```sh
terraform plan -out=tf.out
terraform apply tf.out
```

This still results in the error of working on `empty list`:

```
                                                                                                                                                                                              
Error: Error in function call: Call to function "element" failed: cannot use element function with an empty list.                                                                             
                                                                                                                                                                                              
                                                                                                                                                                                              
                                                                                                                                                                                              
Error: Error in function call: Call to function "element" failed: cannot use element function with an empty list.                                                                             
                                                                                                                                                                                              


Error: Error in function call: Call to function "element" failed: cannot use element function with an empty list.
```

**Comment by evrardjp** [comment]
> ```shell
> terraform plan -out=tf.out
> terraform apply tf.out
> ```
> 
> This still results in the error of working on `empty list`:

Weird, I haven't got this on my machine. Will try again just to be double checking. Which provider are you using that caused this ?

**Comment by evrardjp** [comment]
Double checked on OpenStack provider, and works for me.

**Comment by evrardjp** [comment]
You're right, it happens at the almost end when applying the tf.out file. The apply without the out file works fine though.

**Comment by evrardjp** [comment]
The plan here is to build a minimum reproducible test case in an issue upstream, and discuss the approach there. We could then either change our tf files, or fix it upstrem, based on their input.

We also might want to track in the doc where we used the plan output file, and think of removing that practice, as the very simple case of an `terraform 0.12upgrade` / `terraform validate ` / add little fixes / `terraform plan && terraform apply` just works...

**Comment by evrardjp** [comment]
If packaging is done, we could use it for merging this.

Not sure yet how to make this work, as I am not sure how the CI jobs/workers are set up.
If they are installing tf in the test, it would allow the right version of tf to be merged at the same time as this.
If not, we'll need to install latest tf and break things temporarily (for solving the chicken and egg problem)

**Comment by Itxaka** [comment]
> These are the automatic and manual operations to perform for a terraform 0.12
upgrade.

@evrardjp  What are the manual operations to perform? Is that something that we could do on package install?

**Comment by evrardjp** [comment]
@Itxaka assuming people still have manual operations, I don't think we should make the packaging more complex. Let's just write release notes, pointing to a two commands and a series of text files to edit.

**Comment by evrardjp** [comment]
Don't be sorry, it's fine. People should still review it though.

**Comment by mjura** [comment]
I have tested it and works fine

**Comment by evrardjp** [comment]
I think we can remove the ``Do not merge`` label too.

**Comment by evrardjp** [comment]
I have updated everything based on my discussion with Klaus from yesterday. This is ready for review, even if it breaks CI.

**Comment by evrardjp** [comment]
Hello @atighineanu , could you have a look at this? We would like QA to have a definitive look at it, before going further. You'll need terraform from upstream to test this. For the instructions on how to do things, please check the documentation that will be applied when we'll have our package released here: https://github.com/SUSE/caasp-release-notes/pull/26

**Comment by davidcassany** [comment]
This PR depends on updated Terraform package. The update is on it's way [here](https://build.suse.de/package/show/SUSE:Maintenance:13880/terraform.SUSE_SLE-15-SP1_Update). Please to not merge until the maintenance updated is finalized

**Comment by atighineanu** [comment]
Scenario 02 for TF 0.12.19 testing (openstack):
* Cloning skuba 
* Deploying on openstack lb1:m1:w1 cluster using terraform 0.11.14    PASSED
* Bootstrapping with skuba (from cloned repo) using specified infra folder in skuba PASSED
* Running skuba cluster status     PASSED

* Installing Terraform 0.12.19
* Fetching the #872 PR into skuba repository (git pull skuba; git fetch skuba pull/872/head:pr872; git checkout pr872)
---------------
* make new skuba
* Running skuba cluster status           PASSED
* Running terraform init (inside the /home/whoami/go/src/skuba/ci/infra/openstack/)    PASSED
* Running terraform refresh                 PASSED
* Running terraform output                  PASSED
* Running terraform destroy                PASSED
"""
Scenario 03 for TF 0.12.19 testing (openstack):
* Cloning skuba 
* Fetching the #872 PR into skuba repository (git pull skuba; git fetch skuba pull/872/head:pr872; git checkout pr872)
* Installing Terraform 0.12
* Bootstrapping with latest skuba  using specified infra folder in skuba          PASSED
* Running skuba cluster status           PASSED
* Running terraform init (inside the /home/whoami/go/src/skuba/ci/infra/openstack/)    PASSED
* Running terraform refresh                 PASSED
* Running terraform output                  PASSED
* Running terraform destroy                PASSED
===
Openstack looks fine...                        PASSED

**Comment by jordimassaguerpla** [comment]
> Scenario 02 for TF 0.12.19 testing (openstack):
> 
>     * Cloning skuba
> 
>     * Deploying on openstack lb1:m1:w1 cluster using terraform 0.11.14    PASSED
> 
>     * Bootstrapping with skuba (from cloned repo) using specified infra folder in skuba PASSED
> 
>     * Running skuba cluster status     PASSED
> 
>     * Installing Terraform 0.12.19
> 
>     * Fetching the #872 PR into skuba repository (git pull skuba; git fetch skuba pull/872/head:pr872; git checkout pr872)
> 
> 
>     * make new skuba
> 
>     * Running skuba cluster status           PASSED
> 
>     * Running terraform init (inside the /home/whoami/go/src/skuba/ci/infra/openstack/)    PASSED
> 
>     * Running terraform refresh                 PASSED
> 
>     * Running terraform output                  PASSED
> 
>     * Running terraform destroy                PASSED
>       """
>       Scenario 03 for TF 0.12.19 testing (openstack):
> 
>     * Cloning skuba
> 
>     * Fetching the #872 PR into skuba repository (git pull skuba; git fetch skuba pull/872/head:pr872; git checkout pr872)
> 
>     * Installing Terraform 0.12
> 
>     * Bootstrapping with latest skuba  using specified infra folder in skuba          PASSED
> 
>     * Running skuba cluster status           PASSED
> 
>     * Running terraform init (inside the /home/whoami/go/src/skuba/ci/infra/openstack/)    PASSED
> 
>     * Running terraform refresh                 PASSED
> 
>     * Running terraform output                  PASSED
> 
>     * Running terraform destroy                PASSED
>       ===
>       Openstack looks fine...                        PASSED

Hi Alexei,

could you tell us which terraform RPM did you use in your tests? Just to be on the safe side. Thanks.

**Comment by atighineanu** [comment]
> Hi Alexei,
> 
> could you tell us which terraform RPM did you use in your tests? Just to be on the safe side. Thanks.
I've used the binary downloaded directly from hashicorp, the version I indicated in the scenario:
0.12.19
---
here is the TF version output:
sh-4.4# terraform version
Terraform v0.12.19
---
here is the link to the binary zip:
https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip

**Comment by jordimassaguerpla** [comment]
> > Hi Alexei,
> > could you tell us which terraform RPM did you use in your tests? Just to be on the safe side. Thanks.
> > I've used the binary downloaded directly from hashicorp, the version I indicated in the scenario:
> > 0.12.19
> 
> ## here is the TF version output:
> sh-4.4# terraform version
> Terraform v0.12.19
> 
> here is the link to the binary zip:
> https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip

I would have expected you used the RPM that will be released in SLE15SP1: https://build.suse.de/package/show/SUSE:Maintenance:13880/terraform.SUSE_SLE-15-SP1_Update .

Can I ask you to check with that RPM so we are safe to release it in SLE15SP1? There will be a release request later, but qam-caasp is not yet a reviewer so I don't think this will show up in your list.

**Comment by atighineanu** [comment]
> > > Hi Alexei,
> > > could you tell us which terraform RPM did you use in your tests? Just to be on the safe side. Thanks.
> > > I've used the binary downloaded directly from hashicorp, the version I indicated in the scenario:
> > > 0.12.19
> > 
> > 
> > ## here is the TF version output:
> > sh-4.4# terraform version
> > Terraform v0.12.19
> > here is the link to the binary zip:
> > https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip
> 
> I would have expected you used the RPM that will be released in SLE15SP1: https://build.suse.de/package/show/SUSE:Maintenance:13880/terraform.SUSE_SLE-15-SP1_Update .
> 
> Can I ask you to check with that RPM so we are safe to release it in SLE15SP1? There will be a release request later, but qam-caasp is not yet a reviewer so I don't think this will show up in your list.

Yes, I can, but this will have to wait until end of the week, or beginning of next week. I got on my plate 3x cloud-init MRs that are urgent also.

**Comment by jordimassaguerpla** [comment]
> > > > Hi Alexei,
> > > > could you tell us which terraform RPM did you use in your tests? Just to be on the safe side. Thanks.
> > > > I've used the binary downloaded directly from hashicorp, the version I indicated in the scenario:
> > > > 0.12.19
> > > 
> > > 
> > > ## here is the TF version output:
> > > sh-4.4# terraform version
> > > Terraform v0.12.19
> > > here is the link to the binary zip:
> > > https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip
> > 
> > 
> > I would have expected you used the RPM that will be released in SLE15SP1: https://build.suse.de/package/show/SUSE:Maintenance:13880/terraform.SUSE_SLE-15-SP1_Update .
> > Can I ask you to check with that RPM so we are safe to release it in SLE15SP1? There will be a release request later, but qam-caasp is not yet a reviewer so I don't think this will show up in your list.
> 
> Yes, I can, but this will have to wait until end of the week, or beginning of next week. I got on my plate 3x cloud-init MRs that are urgent also.

Ok. In any case we have to wait for maint-coord and "qam-public-cloud", so I do not expect this to happen before next week.

**Comment by pablochacin** [comment]
Superceeded by https://github.com/SUSE/skuba/pull/945/commits

**Pull request closed without merging**
