### PR TITLE
Use dynamic addresses in libvirt

### PR DESCRIPTION
**Pull request by pablochacin**
## Why is this PR needed?

Existing terraform configuration for libvirt assigs fixed addresses to instances. This prevents multiple clusters to be deployed on the same network, as described in https://github.com/SUSE/avant-garde/issues/1297

## What does this PR do?

Modifies terraform files to use addresses dynamically assigned by the network using dhcp.

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by pablochacin** [comment]
@davidcassany the changes are quite straightforward: instead of assigning a fixed ip address with the [`cirdhost function`](https://www.terraform.io/docs/configuration/functions/cidrhost.html) the address dynamically assigned by libvirt is used. 

This PR should run in the kvm pipeline  https://ci.suse.de/job/caasp-jobs/job/v4/job/pr/job/test-libvirt/view/change-requests/job/PR-1042/

**Comment by pablochacin** [comment]
libvirt tests keep failing for this PR. The observed sympton is that cloud init fails in some nodes. 
In testrunner's output we can see this message:
``` 
2020-04-17 10:34:20 ERROR] 
Error: error executing "/tmp/terraform_1078826367.sh": Process exited with status 1
2020-04-17 10:34:20 ERROR] Error: error executing "/tmp/terraform_1078826367.sh": Process exited with status 1
```

Unfortunately, the message doesn't indicate which node failed, so every node must be checked. Using the ip address from `tfout.json`  the following command is used to identifie the nodes:
```
ssh -i id_shared sles@<ip address> cloud-init status
status: error
```

When looking at the '/var/log/cloud-init.log` in the failed node(s) we can see this message:
```
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/runcmd']
Exit code: 106
``` 

The failed script `/var/lib/cloud/instances/scripts/runcmd`  is: 
```
#!/bin/sh
'zypper' '-n' 'install' 'kernel-default' '-kernel-default-base' 'ca-certificates-suse'
```

Also from `/var/log/cloud-init-output.log` we find the following messages which are not shown in the nodes that complete the cloud-init successfully:
```
Repository 'basesystem_pool' is invalid.
[basesystem_pool|http://download.suse.de/ibs/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Warning: Skipping repository 'basesystem_pool' because of the above error.
```
Notice that the url for the repo is the same in the nodes which complete the cloud-init successfully.

**Comment by pablochacin** [comment]
In order to validate if the repository is reachable at the moment of the zypper update, the following command was added to the cloud-init: `curl -v http://download.suse.de/ibs/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/repodata/repomd.xml`

As can be seen below, even when the `curl` command successfully retrieves the content from the repository, the zypper command fails:
<details>
<summary>click to see full output</summary>

```
* TCP_NODELAY set
* Connected to download.suse.de (149.44.176.1) port 80 (#0)
> GET /ibs/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/repodata/repomd.xml HTTP/1.1
> Host: download.suse.de
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Fri, 17 Apr 2020 13:53:13 GMT
< server: Apache/2.4.41 (Linux/SUSE)
< last-modified: Sat, 25 May 2019 19:04:04 GMT
< etag: "239b-589bafa8cb100"
< accept-ranges: bytes
< content-length: 9115
< content-type: text/xml
< 
{ [3810 bytes data]
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
  <revision>1558811030</revision>
  <tags>
    <repo>obsproduct://build.suse.de/SUSE:SLE-15-SP1:GA/sle-module-basesystem/15.1/x86_64</repo>
  </tags>
  <data type="primary">
    <location href="repodata/d2d1c47b7f3f0329b27581e1c5363cb49bf7c0ef137ced0ac5e9291e2db7d989-primary.xml.gz"/>
    <checksum type="sha256">d2d1c47b7f3f0329b27581e1c5363cb49bf7c0ef137ced0ac5e9291e2db7d989</checksum>
    <timestamp>1558811030</timestamp>
    <size>1393683</size>
    <open-size>10046555</open-size>
    <open-checksum type="sha256">332131a7325407ccffdec721bcb59a74a83fbdb5532d365b239bc1a3f4d5f2a5</open-checksum>
  </data>
     .
     .
     .
</repomd>

Retrieving repository 'basesystem_pool' metadata [.error]
Repository 'basesystem_pool' is invalid.
[basesystem_pool|http://download.suse.de/ibs/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
```
</details>

**Comment by pablochacin** [comment]
Probably unrelated, but the cloud-init includes the following boot commands:
```
bootcmd:
  - ip link set dev eth0 mtu 1400
  # Hostnames from DHCP - otherwise localhost will be used
  - /usr/bin/sed -ie "s#DHCLIENT_SET_HOSTNAME=\"no\"#DHCLIENT_SET_HOSTNAME=\"yes\"#" /etc/sysconfig/network/dhcp
  - netconfig update -f
```

In all the nodes, the `DHCLIENT_SET_HOSTNAME` is set to 'YES', however, in all the failing nodes the actual value of the `hosname` is `localhost` while in the other nodes is set properly from dhcp.

**Comment by davidcassany** [comment]
> Probably unrelated, but the cloud-init includes the following boot commands:
> 
> ```
> bootcmd:
>   - ip link set dev eth0 mtu 1400
>   # Hostnames from DHCP - otherwise localhost will be used
>   - /usr/bin/sed -ie "s#DHCLIENT_SET_HOSTNAME=\"no\"#DHCLIENT_SET_HOSTNAME=\"yes\"#" /etc/sysconfig/network/dhcp
>   - netconfig update -f
> ```
> 
> In all the nodes, the `DHCLIENT_SET_HOSTNAME` is set to 'YES', however, in all the failing nodes the actual value of the `hosname` is `localhost` while in the other nodes is set properly from dhcp.

I see not direct relation to the issue we are facing here, however I am pretty convinced that the `DHCLIENT_SET_HOSTNAME` configuration has no effect with the current setup. Libvirt DHCP server does not know which hostname should be providing for each client, thus it just provides the hostname announced by the client, which is `localhost`. Libvirt is not configured to provide dynamic hostnames, so this `DHCLIENT_SET_HOSTNAME` doesn't make much sense here IMHO.

As far as I know libvirt cannot be configured to provide dynamic hostnames by using the standard network XML config file. However it has the possibility to add additional namespace on network configuration to by pass options to the underlying[ dnsmasq service ](https://libvirt.org/formatnetwork.html#elementsNamespaces)(pure bypass no validation at all). I am trying to figure out how to force dnsmasq to provide dynamic hostnames.

**Comment by davidcassany** [comment]
> I see not direct relation to the issue we are facing here, however I am pretty convinced that the `DHCLIENT_SET_HOSTNAME` configuration has no effect with the current setup

This is wrong, libvirt is capable to do so. Adding a small sleep broke some race condition and hostname is properly set. Looks like there is a race condition between the setup of the client hostname from DHCP (or some other network related stuff) and clout-init.

**Comment by kkaempf** [comment]
What is this waiting for ?

**Pull request merged**
