### PR TITLE
Release caasp 4.5.0

### PR DESCRIPTION
**Pull request by dirkmueller**
## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by pablochacin** [comment]
PR is failing. From what I can tell, it looks like this PR hasn't been rebased so the PR pipeline code is outdated.

**Comment by dirkmueller** [comment]
@pablochacin its not outdated. the tests fail because in https://github.com/SUSE/skuba/pull/1302/commits/0ad0bdcb5896c8f23de5eecc28a1902364d1de72 was incorrectly working around a missing cherry-pick, which broke lint check. 

also, the patch to skip testing release branches wasn't backported to the release branch ..

**Comment by pablochacin** [comment]
I see @dirkmueller The problem I have is that we don't backport those changes to release branches. Release branches are tested by QA, not by the CI. That is we did not forget to backport. We intentionally did not pick them. However, as this PR has no comments, I don't know/understand the context or the purpose of this backport. Maybe You or @jordimassaguerpla can explain that. Thanks.

**Comment by pablochacin** [comment]
@dirkmueller  after our conversation in the release-coordination channel, I think the changes needed for running the testrunner locally are these

**Comment by pablochacin** [comment]
Sorry, this is also needed

https://github.com/SUSE/skuba/pull/1317/commits/d5eea1b0b7f3f0dbe643b8adcdc61d59abe2d411

**Comment by dirkmueller** [comment]
@pablochacin did so as you asked. now CI is failing again, but I hope we get ignore that now.

**Comment by dirkmueller** [comment]
rebased on top of the linter fixes..

**Pull request merged**
