### PR TITLE
removed recommends from node install

### PR DESCRIPTION
**Pull request by Klaven**
## Why is this PR needed?
`--recommends` installs child recommended packages as well and bloats the install.
removed failing tests, will add tests too new branch and wait for a fix
I guess we can merge? @jordimassaguerpla 

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?
please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by ereslibre** [comment]
Maybe we could keep the test because we should ensure that these packages are installed. However, for accepting this PR we need to make sure that these packages are pulled as regular dependencies.

cc/ @jordimassaguerpla @davidcassany

**Comment by tdaines42** [comment]
I'd say lets keep the test and modify it.

**Comment by NunoFilipeSantos** [comment]
@ereslibre @tdaines42 what direction are we going?

**Comment by ereslibre** [comment]
I think we should remove the `--recommends`, keeping the test, and ensuring that this kind of dependencies are pulled as regular strong dependencies, instead of recommends, so we can remove the `--recommends` from the `zypper install` command, that will include many other packages that we don't need.

**Comment by kkaempf** [comment]
While I'm in favor of removing the `--recommends`, this PR does not fix the [underlying problem](https://github.com/SUSE/avant-garde/issues/846).

Please don't merge without addressing the actual problem.

**Comment by kkaempf** [comment]
> While I'm in favor of removing the `--recommends`, this PR does not fix the [underlying problem](https://github.com/SUSE/avant-garde/issues/846).
> 
> Please don't merge without addressing the actual problem.

Well, fixing the underlying problem is harder than expected and we agreed to do a workaround by adding documentation.

This PR **must not** be merged without a respective documentation update.

**Comment by Klaven** [comment]
Tests for installed packages where removed.
initial docs where created: https://github.com/SUSE/doc-caasp/pull/546. Once those are finished and merged we can merge the above PR.
/hold

**Comment by jordimassaguerpla** [comment]
Docs are merged.
@Klaven back to you now ;)

**Comment by jordimassaguerpla** [comment]
@pablochacin The failing tests looks like the issue you are working on. How do we proceed? Do we merge this? Do we rebase? Do we wait? Thanks

**Comment by Klaven** [comment]
@ereslibre please review
@jordimassaguerpla everything is fine in the PR, just some flaky tests. I think it can be merged now.

**Pull request merged**
