### PR TITLE
Push ci changes to maintenance v4

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
## Why is this PR needed?

We need to merge the CI changes done in experimental v5 branch to the maintenance v4 branch or the CI won't work for maintenance v4 branch.

Fixes #1662

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

merge CI changes from experimental v5 branch to maintenance v4 branch

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
@pablochacin Tests are failing. Do you think this is relevant for this PR?

**Comment by jordimassaguerpla** [comment]
This is the error

`2020-06-11 09:00:37 DEBUG] Executing command

    cwd: /home/jenkins/workspace/caasp-jobs_pr_test_PR-1139/skuba/ci/infra/vmware 

    env: {'SSH_AUTH_SOCK': '/tmp/4-caasp-jobs-pr-test-PR-1139/agent.sock', 'PATH': '/home/jenkins/workspace/caasp-jobs_pr_test_PR-1139/py3venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'}

    cmd: source ****; terraform destroy -auto-approve -var stack_name=4-caasp-jobs-pr-test-PR-1139

2020-06-11 09:00:37 DEBUG] var.template_name

2020-06-11 09:00:37 DEBUG] Enter a value: 

2020-06-11 09:00:37 DEBUG] var.vsphere_datacenter

2020-06-11 09:00:37 DEBUG] Enter a value: 

2020-06-11 09:00:37 DEBUG] var.vsphere_network

2020-06-11 09:00:37 DEBUG] Enter a value: 

2020-06-11 09:00:37 DEBUG] var.vsphere_resource_pool

2020-06-11 09:00:37 DEBUG] Enter a value: 


2020-06-11 09:00:38 ERROR] 

Error: Could not satisfy plugin requirements

2020-06-11 09:00:38 ERROR] Error: Could not satisfy plugin requirements


2020-06-11 09:00:38 ERROR] 


2020-06-11 09:00:38 ERROR] 

Plugin reinitialization required. Please run "terraform init".

2020-06-11 09:00:38 ERROR] Plugin reinitialization required. Please run "terraform init".
`

**Comment by jordimassaguerpla** [comment]
Could we be missing a commit?

**Comment by pablochacin** [comment]
The actual error is this: 
<details>
<summary>
CONFLICT (content): Merge conflict in ci/jenkins/jobs.yaml
</summary>
```
+ make -f skuba/ci/Makefile pr_checks
/home/jenkins/workspace/asp-jobs_pr_test-libvirt_PR-1139/skuba/ci/tasks/rebase.py
First, rewinding head to replay your work on top of it...
Applying: Reorganize jobs per caasp version
Using index info to reconstruct a base tree...
M	ci/jenkins/jobs.yaml
M	ci/jenkins/templates/conformance-template.yaml
Falling back to patching base and 3-way merge...
Auto-merging ci/jenkins/templates/conformance-template.yaml
CONFLICT (content): Merge conflict in ci/jenkins/templates/conformance-template.yaml
Auto-merging ci/jenkins/jobs.yaml
CONFLICT (content): Merge conflict in ci/jenkins/jobs.yaml
error: Failed to merge in the changes.
Patch failed at 0001 Reorganize jobs per caasp version
The copy of the patch that failed is found in: .git/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

Command 'git -c "user.name=CaaSP Jenkins" -c "user.email=containers-bugowner@suse.de"                    rebase origin/master' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/jenkins/workspace/asp-jobs_pr_test-libvirt_PR-1139/skuba/ci/tasks/rebase.py", line 20, in <module>
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'git -c "user.name=CaaSP Jenkins" -c "user.email=containers-bugowner@suse.de"                    rebase origin/master' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/workspace/asp-jobs_pr_test-libvirt_PR-1139/skuba/ci/tasks/rebase.py", line 23, in <module>
    print(Format.alert("Rebase failed, manual rebase is required."))
NameError: name 'Format' is not defined
make: *** [skuba/ci/Makefile:60: git_rebase_check] Error 1
script returned exit code 2
```
</details>

**Comment by pablochacin** [comment]
Notice the problem was not reported due to this exception:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/asp-jobs_pr_test-libvirt_PR-1139/skuba/ci/tasks/rebase.py", line 23, in <module>
    print(Format.alert("Rebase failed, manual rebase is required."))
NameError: name 'Format' is not defined
```

**Comment by jordimassaguerpla** [comment]
Against which branch is it rebasing?

**Comment by jordimassaguerpla** [comment]
> Against which branch is it rebasing?

should I change these to be maintenance-caasp-v4 instead of master?

`branch_name   = os.getenv("BRANCH_NAME","master")`

https://github.com/SUSE/skuba/blob/maintenance-caasp-v4/ci/tasks/rebase.py#L9

rebase origin/master'.format(change_author, author_email)

https://github.com/SUSE/skuba/blob/maintenance-caasp-v4/ci/tasks/rebase.py#L18

**Comment by pablochacin** [comment]
@jordimassaguerpla  I'm still diagnosing the issue. I'll update the card when I have more information.

**Comment by pablochacin** [comment]
PR https://github.com/SUSE/skuba/pull/1158 should fix the issue with the rebase.

@jordimassaguerpla  can you cherry-pick the changes in https://github.com/SUSE/skuba/pull/1158 and add to this PR?

**Comment by jordimassaguerpla** [comment]
> PR #1158 should fix the issue with the rebase.
> 
> @jordimassaguerpla can you cherry-pick the changes in #1158 and add to this PR?

done

**Comment by jordimassaguerpla** [comment]
@pablochacin tests pass :) . Should I merge?

**Comment by pablochacin** [comment]
Yes, test pass but the logic for multiple PR target branches is somehow broken:
```
+ make -f skuba/ci/Makefile pr_checks
/home/jenkins/workspace/caasp-jobs_pr_test_PR-1158/skuba/ci/tasks/rebase.py
Not a PR. Rebase not required.
```

**Comment by pablochacin** [comment]
@jordimassaguerpla https://github.com/SUSE/skuba/pull/1158 should be fixed. If you can cherry-pick it, I think this time it should pass.

**Pull request merged**
