### PR TITLE
Fix skuba-update --version always 0.0.0 (bsc#1160463)

### PR DESCRIPTION
**Pull request by jenting**
## Why is this PR needed?

Fix `skuba-update --version` always print `0.0.0`

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

Create the VERSION file for skuba-update, and then, the `skuba-update/setup.py` would read the VERSION file.

## Anything else a reviewer needs to know?

N/A

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

N/A
### Status **BEFORE** applying the patch

- SSH into one of the node
- Execute `skuba-update --version`

### Status **AFTER** applying the patch

- SSH into one of the node
- Execute `skuba-update --version`

## Docs

N/A

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by innobead** [comment]
@jordimassaguerpla could you or someone familiar to help add a README file in https://github.com/SUSE/skuba/tree/master/ci/packaging to explain how scripts inside work? or we already have? Thanks.

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla could you or someone familiar to help add a README file in https://github.com/SUSE/skuba/tree/master/ci/packaging to explain how scripts inside work? or we already have? Thanks.

https://github.com/SUSE/skuba/blob/master/CONTRIBUTING.md#releasing

It is the "make suse-package" command.

**Comment by jordimassaguerpla** [comment]
I do not think this commit is enough. So you are creating the VERSION file in the BUILD directory but this is not being installed afterwards.

You should get the VERSION file installed in the buildroot and then add it to the %files section. I would expect this file to be in /usr/share/ or some similar directory. See https://ca.wikipedia.org/wiki/Filesystem_Hierarchy_Standard on where to put things.

**Comment by jenting** [comment]
> I do not think this commit is enough. So you are creating the VERSION file in the BUILD directory but this is not being installed afterwards.
> 
> You should get the VERSION file installed in the buildroot and then add it to the %files section. I would expect this file to be in /usr/share/ or some similar directory. See https://ca.wikipedia.org/wiki/Filesystem_Hierarchy_Standard on where to put things.

I was trying to fulfill the `setup.py` requirement
https://github.com/SUSE/skuba/blob/16976a93382ed029976f00bdbd2fd5d64d13291c/skuba-update/setup.py#L22-L34

So, is the generated VERSION file have to in /use/share or some similar directory?

**Comment by jordimassaguerpla** [comment]
> > I do not think this commit is enough. So you are creating the VERSION file in the BUILD directory but this is not being installed afterwards.
> > You should get the VERSION file installed in the buildroot and then add it to the %files section. I would expect this file to be in /usr/share/ or some similar directory. See https://ca.wikipedia.org/wiki/Filesystem_Hierarchy_Standard on where to put things.
> 
> I was trying to fulfill the `setup.py` requirement
> 
> https://github.com/SUSE/skuba/blob/16976a93382ed029976f00bdbd2fd5d64d13291c/skuba-update/setup.py#L22-L34
> 

Then this looks good. Sorry for the confusion.

**Pull request merged**
