### PR TITLE
AWS fix deployment

### PR DESCRIPTION
**Pull request by flavio**
## Why is this PR needed?

This PR includes several fixes that are needed to be able to deploy v4 clusters on top of AWS.

The most notable fix is the one for [bsc#1146774](https://bugzilla.suse.com/show_bug.cgi?id=1146774).

## What does this PR do?

Critical fixes:
  * Do not use hard coded AMI IDs: these IDs change over the time and are dependent on the AWS region being used. To solve the problem the terraform files take advantage of a SUSE-dedicated [data source](https://github.com/SUSE/terraform-provider-susepubliccloud). This data source fetches the AMI in a dynamic fashion from a REST API that is owned and maintained by the SUSE Public Cloud team. This is recommended way to proceed
  * Ensure the right AMI is being used:
     - We have to pick the *"container host AMI"* to avoid issues like [bsc#1146774](https://bugzilla.suse.com/show_bug.cgi?id=1146774). This is an AMI built by the SUSE Public Cloud team to act as a container host, due to that it has some optimizations (like the network related one).
     - We have to use a *"BYOS"* (Bring Your Own Subscription) AMI: currently there's no way to register a SLE system against a "Public Cloud team - maintained" RMT instance and then add product channels using a personal registration key. Previous to this PR the code used a "pre-registered" AMI, de-registred it and registered it against SCC/a customer owned RMT server using user credentials. With a BYOS AMI this is no longer needed.
  * Cleanup docker iptable leftovers: **all** the cloud AMIs come with docker running. In addition to removing the docker package we should also cleanup all the iptable rules and table it creates. This is done to avoid issues with kube-proxy later.
  * Fix multi master clusters: the previous code didn't pass terraform planning phase when more than a master was used
  * Remove some cloud-init commands designed for old AWS images: the cri-o package doesn't come with BTRFS hard coded anymore
  * Enable CPI integration
  * Allow cluster VPC to be connected to existing VPCs: this allows the cluster to consume resources hosted by the same organization inside of other VPC (eg: SUSE Manager)
  * Allow registration against SUSE Manager

Minor changes:
  * Move aws keypair definition out of the file defining security group rules.

## Anything else a reviewer needs to know?

* The PR is relatively big, you can have a better time reviewing it at a commit level: you will know exactly why something has been changed
* This is an **unsupported** deployment platform for CaaSP v4 at **this** point in time. The final package we ship doesnt' include any of these files.
* We are introducing a new package dependency: [terraform-provider-susepubliccloud](https://github.com/SUSE/terraform-provider-susepubliccloud). There's currently a FATE open to include this code into the public cloud module. In the meantime we can ignore the lack of a supported SLES package for this provider because AWS deployment is currently unsupported.

## Info for QA

The AWS deployment is currently unsupported. At this stage no help is needed from QA.

However, if really wanted, the whole code can be tested by following these steps:

  * Require an AWS account on openbare
  * Fill the mandatory information inside of a `terraform.tfvars` file
  * Create the cluster `terraform apply`
  * Use skuba against the nodes

## Docs

No documentation is needed at this point

# Merge restrictions after RC

I'm not editing that :), but I think we can merge this PR (like previous ones about AWS) because:
  * the code is self-isolated (lives inside of a single directory)
  * the code is not referenced by anything used in production
  * the code is not even part of the build artifacts (the whole directory is not part of the skuba RPM)

(Please do not edit this)

This is the "better safe than sorry" phase, so we will restrict who and what can be merged to prevent unexpected surprises:

    Who can merge: Release Engineers*
    What can be merged (merge criteria):
        3 approvals:
            1 developer
            1 manager (Nuno, Flavio, Klaus, Markos, Stef, David, Rafa or Jordi)
            1 QA
        there is a PR for updating documentation (or a statement that this is not needed)
        it fixes a P2 bug that has not been target for maintenance
        the impact is low: for example, it does not touch a piece of code that has an impact on all features

* *Managers will keep the permissions, but they are supposed to give approval. Merging will be done by Release Engineers because they will coordinate the release of the fix.*

### CODE REVIEW

**Comment by danielorf** [comment]
Looks good.  Ready to approve, but...

> This is an unsupported deployment platform for CaaSP v4 at this point in time. The final package we ship doesnt' include any of these files. 

Should we mark this as `Do Not Merge` for now?  Or is it sufficient that the RPM spec file doesn't copy anything from ` ci/infra/aws`?  I can envision the situation where a customer spots this in the code and wonders why skuba is missing the functionality.

**Comment by flavio** [comment]
The whole AWS deployment has been into git since the early days of the project. We never shipped that into the RPM.

I would say we can merge it, as we did with some recent fixes I pushed over in the last weeks.

**Comment by jordimassaguerpla** [comment]
@flavio we need a QA approval, even to say this does not need to be tested. @fgerling can you check?

**Comment by fgerling** [comment]
We will check on this after GMC as this is not (yet) supported and GMC has priority.

**Comment by rssfed23** [comment]
Error: Error applying plan:

4 error(s) occurred:

* aws_instance.nodes[0]: 1 error(s) occurred:

* aws_instance.nodes.0: Error launching source instance: InvalidParameterValue: Value (caasp-k8s-worker-vm-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: f955d665-924a-476b-9728-16a7457ace78
* aws_instance.control_plane: 1 error(s) occurred:

* aws_instance.control_plane: Error launching source instance: InvalidParameterValue: Value (caasp-k8s-master-vm-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: 70748c79-7874-4575-93ef-189fad1241c2
* aws_instance.nodes[1]: 1 error(s) occurred:

* aws_instance.nodes.1: Error launching source instance: InvalidParameterValue: Value (caasp-k8s-worker-vm-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: 6a0199c0-655d-41b4-a8c0-f4d0868bc757
* aws_instance.nodes[2]: 1 error(s) occurred:

* aws_instance.nodes.2: Error launching source instance: InvalidParameterValue: Value (caasp-k8s-worker-vm-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: df8f22c8-8ee2-4dc1-a0bb-98e67665f50e```

I resolved this by manually adding the 2 IAM roles in the IAM UI which automatically created the profiles of the same name and after that; volia. But you might want to add the roles into the terraform.

Also; as this has the dependency on the cloud provider terraform scripts and that team doesn't put instructions on how to actually install the plugin can you add a quick note on how to do that into the readme?
(For the many non-(open)sles users out there I had to download the RPM from OBS, extract it, extract the CIPO then figure out which directory to actually put it in as the terraform instructions were not clear (in the end ~/.terraform.d/plugins and rename it to terraform-provider-susepubliccloud to get it to work). Believe it or not this part took the most time.
I'd also add a quick note on the variables.tf file. For someone not new to terraform knowing to head there to increase node counts/node sizes is important.

Some notes on potential future changes though:
I believe it's AWS best practice to span the worker nodes across AZs so we should document how to do that.
Also, I believe in AWS world they like to create private and public subnets, put all the workers in the private subnet and master in the public one with a ELB like you've done but the workers should always be private and more isolated (although this can cause nodeport issues so it's a decision up to Engineering I guess. I know the Cloud team made their EKS Quickstart did this so you couldn't ssh to workers directly and had to use a bastion host inside the private net for access). But I'd say all of this (aside from multi-AZ support) is v2 work as most importantly it gets a cluster up and running with minimal effort.

(AWESOME WORK btw :) - out of all of our product Quickstarts/Terraforms yours was the ONLY one I was able to get done pretty much first time. The CAP QS has never worked for me, the SAP HANA one has a couple odd bugs in that require intervention and don't even get me started on Sumaform i gave up after a couple of hours and did it manually (admittedly that's not designed for customers though).

**Comment by ereslibre** [comment]
@flavio: this needs rebase now.

**Comment by flavio** [comment]
Closing, all the changes go merged with https://github.com/SUSE/skuba/pull/720

**Pull request closed without merging**
