### PR TITLE
Fix duplicate name issues with secgroup handling

### PR DESCRIPTION
**Pull request by dirkmueller**
security groups can have duplicate names, so when specifying a name
that is ambigous deployment or cleanup fails, which leaves trash behind.

Better use ids, those are unique identifiers.

(cherry picked from commit 81f1f0de23d09a0041bde065e609b6c50a7fbd22)

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by pablochacin** [comment]
@jordimassaguerpla should we merge this backport?

**Review by jordimassaguerpla — CHANGES_REQUESTED** [review]
@dirkmueller Which is the issue number or bsc number? Thanks

**Comment by dirkmueller** [comment]
@jordimassaguerpla was this an accidental close? the issue is linked in the master patch which was linked from the patch description and it is now also in the patch description. what else is wrong with this backport?

**Comment by jordimassaguerpla** [comment]
It was accidental. Can you reopen it but to the maintenance-caasp-v4.2 branch?

**Pull request closed without merging**
