### PR TITLE
Patternless cosmetic cleanups

### PR DESCRIPTION
**Pull request by evrardjp**
## Why is this PR needed?

This fixes latest comments on https://github.com/SUSE/skuba/pull/1178

## What does this PR do?

Cosmetic cleanups

## Anything else a reviewer needs to know?

Nothing special

## Info for QA

None

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

## Docs

No change

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by evrardjp** [comment]
This first commit of this series will be automatically removed when I rebase, and the patternless PR is merged.

**Comment by evrardjp** [comment]
This will conflict with stage1 fix, so I propose we do it afterwards :p

**Comment by evrardjp** [comment]
I kept the same kind of logging that the wrapped function, but it could sens to use klog instead.

**Comment by jenting** [comment]
> I kept the same kind of logging that the wrapped function, but it could make sense to use klog.

Ya, I mean we could consider prints out the stderr if present.

**Comment by evrardjp** [comment]
> LGTM. I've however mixed feelings about the `skubaconstants.LastCaaSP4KubernetesVersion`: on one hand I like it, on the other hand we still have references to `1.17` around (like `-patterns-caasp-Node-1.17`).
> 
> Should we leave references like `-patterns-caasp-Node-1.17` as they currently are, should we build their name with `fmt.Sprintf("-patterns-caasp-Node-%s", skubaconstants.LastCaaSP4KubernetesVersion)`, should we drop the constant? I don't have a clear opinion thinking

I sure hope things won't change, so I suppose a constant is fine. readability is not really improved by that, but yeah, I could use that constant for the package. But then for <1.18, I would need to do parsing, then +1, or introduce a new constant, FirstCaaSP5.

I think the noble goal of readability is lost at some point.

I prefered what I did in the first place. Put 1.17 in stone, in the location where I do the work, and put appropriate comments. That's why comments exist.

**Comment by evrardjp** [comment]
Note: I will rebase this on top of the latest changes in my branch, when it's merged in master.

**Comment by evrardjp** [comment]
This is what it looks like. I am not sure it's more readable. Quite the opposite in fact.

**Comment by evrardjp** [comment]
I will rebase this next week.

**Comment by evrardjp** [comment]
Rebased.

**Comment by jordimassaguerpla** [comment]
I see the 5.0.0 label. We are in GMC phase now so only release blockers should be included. Is this "cosmetic cleanup" a release blocker? By the title it does not seem so ... can we have this release as a maintenance update ? If so, please change the label to v5 instead of 5.0.0

**Comment by chentex** [comment]
> I see the 5.0.0 label. We are in GMC phase now so only release blockers should be included. Is this "cosmetic cleanup" a release blocker? By the title it does not seem so ... can we have this release as a maintenance update ? If so, please change the label to v5 instead of 5.0.0

This just needs one more approve to be merged.

**Pull request merged**
