### PR TITLE
Add CI feedback questionaire to the pull request template

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
so that users can give feedback

### CODE REVIEW

**Comment by pablochacin** [comment]
Not convinced of this. I mean, the PR template is already complex and asking for feedback while people in the middle of setting this up it's maybe not the best moment. My 2 cents

**Comment by jordimassaguerpla** [comment]
> Not convinced of this. I mean, the PR template is already complex and asking for feedback while people in the middle of setting this up it's maybe not the best moment. My 2 cents

Where would you put it instead?

thanks

**Comment by drpaneas** [comment]
> Where would you put it instead?

Not here, the PR template is not the place to gather such feedback. Schedule a meeting with the development team and ask them to cast their vote.

My thoughts:
The CI is testing far too many things per pull-request basis. You have integrations tests which talk to infrastructure, spinning VMs and installing software using all sorts of dependencies (network, filesystems, you name it). Unless you run it in a space devoid of matter, this is going to be unreliable. For the PR merge, I would recommend you to run only unit-tests and inject indirect dependencies using mocking.

Integration tests can be handled _outside_ of Github, since you are doing internal infra stuff, which is private anyways.

tldlr; github ci is for merging code. internal ci is for shipping the product.

**Comment by jenting** [comment]
IMO, the PR template should not include a feedback URL.

**Pull request closed without merging**
