### PR TITLE
Don't run the collab check on master

### PR DESCRIPTION
**Pull request by tdaines42**
## Why is this PR needed?

The collab check fails on master because there is no change author. 

## What does this PR do?

This skips the collab check if the job is running on master

## Anything else a reviewer needs to know?

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by jenting** [comment]
What about other branches? Like `release-caasp-4.0-gmc`, it's a hotfix branch, developers would file PR and merged/cherry-pick onto it.

**Comment by tdaines42** [comment]
We aren't running that in CI currently as far as I know. If we decide to then it can be added later.

**Comment by jenting** [comment]
Is it possible to check if it's a PR then run a collaborator check?

**Comment by jenting** [comment]
Two questions to clarify:
1. For the master branch, I saw only 3 pipelines run. Where to set up which pipelines to run? I cannot find in Jenkinsfile
2. Right now all PR needs to rebase onto the target (master) branch, so I don't know why we need to run CI on evey merged commit? IMO, We could move to test the target branch on a nightly test. This will reduce the CI server jobs.

**Comment by tdaines42** [comment]
> Two questions to clarify:
> 
>     1. For the master branch, I saw only 3 pipelines run. Where to set up which pipelines to run? I cannot find in Jenkinsfile
> 
>     2. Right now all PR needs to rebase onto the target (master) branch, so I don't know why we need to run CI on evey merged commit? IMO, We could move to test the target branch on a nightly test. This will reduce the CI server jobs.

Everything is setup using Jenkins Job Builder. 

I think it was just initially set up that way and never changed. It wasn't really hurting anything at the time and runs used to only take ~20 min. We have nightly pipelines running already so we could disable the runs on master if someone wants to do that.

**Comment by jenting** [comment]
I prefer running full pipeline tests (including deployment, bootstrap, join/e2e tests) on every merged commit or running on nightly pipeline. Either way is fine.

**Comment by innobead** [comment]
Following JenTing suggestion, there are 2 things as below. Let’s follow up in other places.

1. Duplicated
2. What checks or tests should be run in PR

**Pull request merged**
