### PR TITLE
Makefile: Add go version check

### PR DESCRIPTION
**Pull request by nirmoy**
skuba requires >= go1.12 for building.
This PR make sure make check that requirement.
Before:
```
make
GO111MODULE=on go install -mod=vendor -ldflags "-X=github.com/SUSE/skuba/pkg/skuba.Version=0.8.1 -X=github.com/SUSE/skuba/pkg/skuba.Commit=8fd48ab -X=github.com/SUSE/skuba/pkg/skuba.BuildDate=20190725" -tags development ./cmd/...
build k8s.io/component-base/config: cannot find module for path k8s.io/component-base/config
make: *** [Makefile:54: install] Error 1
```
After:
```
make
FATAL: Go version should be >= 1.12.x
make: *** [Makefile:77: go-version-check] Error 1
```

### CODE REVIEW

**Comment by jhsiaosuse** [comment]
Go >= 1.11 supports go modules

**Comment by fgerling** [comment]
> Go >= 1.11 supports go modules

Can you elaborate on that? in 1.11 modules are experimental. Did that change in 1.12?

**Comment by nirmoy** [comment]
@jhsiaosuse Thanks. Updated.

**Comment by jhsiaosuse** [comment]
> > Go >= 1.11 supports go modules
> 
> Can you elaborate on that? in 1.11 modules are experimental. Did that change in 1.12?

AFAIK, golang 1.12 does not change go module related but enhance tools related [artifacts](https://golang.org/doc/go1.12). I have used go module from 1.11, everything gonna well.

**Comment by fgerling** [comment]
With `go 1.11`
```bash
root@a902dcfaa641:/go/src/github.com/nirmoy/skuba# git rev-parse HEAD
63a0be4e721301401eed3e6aa446f63b9d50014e

root@a902dcfaa641:/go/src/github.com/nirmoy/skuba# go version
go version go1.11.12 linux/amd64

root@a902dcfaa641:/go/src/github.com/nirmoy/skuba# make
FATAL: Go version should be >= 1.12.x
make: *** [Makefile:77: go-version-check] Error 1
```

With `go 1.12`
```bash
root@0ab3b5df474e:/go/src/github.com/nirmoy/skuba# git rev-parse HEAD
63a0be4e721301401eed3e6aa446f63b9d50014e

root@0ab3b5df474e:/go/src/github.com/nirmoy/skuba# go version
go version go1.12.7 linux/amd64

root@0ab3b5df474e:/go/src/github.com/nirmoy/skuba# make
GO111MODULE=on go install -mod=vendor -ldflags "-X=github.com/SUSE/skuba/pkg/skuba.Version=0.8.1 -X=github.com/SUSE/skuba/pkg/skuba.Commit=63a0be4 -X=github.com/SUSE/skuba/pkg/skuba.BuildDate
=20190725" -tags development ./cmd/...
rm -f /go/bin/kubectl-caasp
ln -s /go/bin/skuba /go/bin/kubectl-caasp
```

LGTM. Thank you @nirmoy.
Anything else I should have a look at?

**Comment by saschagrunert** [comment]
There is a hash sum calculation bug in go 1.11 which will cause a mismatch in go.sum between 1.11 and 1.12: https://github.com/golang/go/issues/29278

**Comment by jhsiaosuse** [comment]
> There is a hash sum calculation bug in go 1.11 which will cause a mismatch in go.sum between 1.11 and 1.12: [golang/go#29278](https://github.com/golang/go/issues/29278) To avoid issues I would stick to 1.12 :)

Thanks, @saschagrunert, I met this issue before.

**Pull request merged**
