### PR TITLE
CI: improve sonobuoy job

### PR DESCRIPTION
**Pull request by Itxaka**
Bring the sonobuoy job in sync with the rest of the jobs by
having just one step for deploying the full cluster.

Also deploy the full cluster (3 masters, 3 nodes by default) as
1) they are already provisioned
2) sonobuoy tests needs at least 2 workers
3) we may introduce disruptive tests in the future which requires HA
4) Fix the current problem in which the apiserver may go down and
because we have just one master it can crash the whole test run

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes https://github.com/SUSE/avant-garde/issues/1366
Fixes https://github.com/SUSE/avant-garde/issues/1367

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by Itxaka** [comment]
This is now passing the conformance tests: https://ci.suse.de/blue/organizations/jenkins/caasp-jobs%2Fv4%2Fconformance%2Fvmware-conformance/detail/vmware-conformance/305/pipeline/

**Comment by pablochacin** [comment]
Added a commit with help for the new command.

**Comment by pablochacin** [comment]
I'm not convinced this code should be placed in testrunner in this way. I'm afraid we are reverting to the "toolbox" model for testrunner that caused issues in the past.  I would like to see a followup PR to address this, maybe incorporate this logic as part of the "deploy-cluster" command we have discussed, passing the "prevent-reboots"  as an option.

**Pull request merged**
