### PR TITLE
Fix `go get` path for executable

### PR DESCRIPTION
**Pull request by saschagrunert**
## Why is this PR needed?

The mentioned path for go get seems not correct, which should be fixed now.

## What does this PR do?

Update the documentation part of the README.md

### CODE REVIEW

**Comment by saschagrunert** [comment]
Am I able to retrigger the jenkins job somehow? :innocent:

**Comment by nirmoy** [comment]
Rebase, not the best way but works

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch, thanks @nirmoy :pray:

**Comment by mssola** [comment]
The failure has nothing to do with this pull request. Can we merge it?

**Comment by stefsuse** [comment]
merging despite vmware test failure - README only change

**Pull request merged**
