### PR TITLE
Remain on kernel-default-base

### PR DESCRIPTION
**Pull request by dirkmueller**
As indicated in https://jira.suse.com/browse/PM-1909 the JeOS team is
interested to learn why kernel-default-base is not good enough, so
lets try without it.

I'll do so in OpenStack first as that is least priority and should help
the z-Squad in not disrupting important work.

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by cmurphy** [comment]
I'm not sure about standard skuba operation so maybe this can be ignored as a special case but we found that NVIDIA drivers require the ipmi_msghandler module which is only provided by kernel-default, not kernel-default-base.

**Comment by dirkmueller** [comment]
@cmurphy agree it is not in kernel-default-base. is that the only module that is missing? I wonder if we can justify moving it to kernel-default-base. in principle the jeos team was open to make the out of the box jeos image work.

**Comment by cmurphy** [comment]
[**@dirkmueller**](https://github.com/dirkmueller) commented on [Jul 7, 2020, 12:18 AM PDT](https://github.com/SUSE/skuba/pull/1229#issuecomment-654650093 "2020-07-07T07:18:19Z - Replied by Github Reply Comments"):
> @cmurphy agree it is not in kernel-default-base. is that the only module that is missing? I wonder if we can justify moving it to kernel-default-base. in principle the jeos team was open to make the out of the box jeos image work.

To my knowledge that is the only one that is needed to support NVIDIA but I'm not sure if there are other modules needed for other components of CaaSP.

**Comment by flavio** [comment]
AFAIK we the `kernel-default-base` was missing some modules needed by cilium.

cc @mrostecki

**Comment by mrostecki** [comment]
Yes, `kernel-default-base` is missing the `vxlan` module. I will check later today if there are more modules missing, but `vxlan` was the main one that made Cilium not working.

**Comment by mrostecki** [comment]
Sorry, I'm closing this. If we really want to switch to `kernel-default-base`, we should start from adding `vxlan` and possibly other modules there.

**Comment by dirkmueller** [comment]
@mrostecki vxlan module is there just fine: 

$ rpm -qpvl /mounts/dist/full/full-sle15-sp2-x86_64/suse/x86_64/kernel-default-base.rpm  | grep vxlan
-rw-r--r--    1 root     root                   123896 Jul 30 11:06 /lib/modules/5.3.18-24.9-default/kernel/drivers/net/vxlan.ko

**Comment by dirkmueller** [comment]
ah, sorry I realize that the only ci testing here is vmware and that doesn't even use kernel-default-base. :-((

**Comment by mrostecki** [comment]
@dirkmueller 

> @mrostecki vxlan module is there just fine:
> 
> ```
> $ rpm -qpvl /mounts/dist/full/full-sle15-sp2-x86_64/suse/x86_64/kernel-default-base.rpm  | grep vxlan
> -rw-r--r--    1 root     root                   123896 Jul 30 11:06 /lib/modules/5.3.18-24.9-default/kernel/drivers/net/vxlan.ko
> ```

Good to know. Last time I tried to use kernel-default-base, it wasn't there. Sorry for not looking into logs and the actual cause of error. I was just like "oh, CI is red, so it's for sure that problem missing modules".

**Comment by dirkmueller** [comment]
the CI failures were definitely unrelated because they only ran against vmware and I didn't touch that code path at all.

**Pull request closed without merging**
