### PR TITLE
 Update terraform files for tf 0.12

### PR DESCRIPTION
**Pull request by Itxaka**
## Why is this PR needed?

Same PR as https://github.com/SUSE/skuba/pull/872 with some changes to make tf0.12 work with our CI. Unfortunately I cannot push to that PR so I had to create a new one as JP is out for a while.

 - Enable tfstate compatibility with tf0.12: Output of terraform.tfstate has changed between 0.11 and 0.12, this patch makes testrunner compatible with both outputs
 - Change old 0/1 into bool in tfvars for CI and examples: 0/1 are not valid bool values anymore on tf0.12 so we need to change those in the examples and the CI values
 - Rebased to master

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by pablochacin** [comment]
LGTM. Not approving yet just in case we need to add more changes.

**Comment by Itxaka** [comment]
rebased

**Comment by pablochacin** [comment]
I updated the PR changing the agent label in jobs to 'caasp-team-private-integration'

**Comment by bbobrov** [comment]
https://build.suse.de/request/show/209910 seems to be merged

**Comment by pablochacin** [comment]
> https://build.suse.de/request/show/209910 seems to be merged

@jordimassaguerpla :point_up:

**Pull request merged**
