### PR TITLE
Update cilium to 1.7.6 and image to rev3

### PR DESCRIPTION
**Pull request by mmnelemane**
## Why is this PR needed?

Fix for  https://bugzilla.suse.com/show_bug.cgi?id=1173559 along with other elements listed in https://github.com/SUSE/avant-garde/issues/1893

Fixes #1303  

## What does this PR do?

Update Cilium to version 1.7.6  and point to rev3 image which uses updated cilium-proxy and dependencies built with the relevant security fixes stated from https://bugzilla.suse.com/show_bug.cgi?id=1173559
## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
I just realized. Because this is the first 1.7.6 release, we do not really need the -rev3. I know I said I needed that.. I was wrong, sorry ;) I assumed we were not updating the cilium version.

**Comment by jordimassaguerpla** [comment]
I any case, using the rev3 help us make sure this image was being pulled instead of registry.suse.de/devel/caasp/4.5/containers/cilium:1.7.6, so it is good that we have rev3.

**Comment by jordimassaguerpla** [comment]
cilium-operator is in Pending state, this could be the issue
see

https://ci.suse.de/blue/rest/organizations/jenkins/pipelines/caasp-jobs/pipelines/pr/pipelines/test/branches/PR-1362/runs/3/log/?start=0

```
cmd: /usr/bin/kubectl --kubeconfig=/home/jenkins/workspace/caasp-jobs_pr_test_PR-1362/test-cluster/admin.conf get pods --namespace=kube-system -o jsonpath="{ range .items[*]}{@.metadata.name}:{@.status.phase};"
2020-09-17 14:57:54 DEBUG] cilium-8zbrv:Running;cilium-cdf9m:Running;cilium-jqz67:Running;cilium-nff5n:Running;cilium-operator-67ff6dfbdf-w6xlg:Pending;cilium-t4vvl:Running;cilium-w5bjj:Running;coredns-84cdf7bd59-rtlxb:Running;coredns-84cdf7bd59-z42ct:Running;etcd-caasp-master-3-caasp-jobs-pr-test-pr-1362-0:Running;etcd-caasp-master-3-caasp-jobs-pr-test-pr-1362-1:Running;etcd-caasp-master-3-caasp-jobs-pr-test-pr-1362-2:Running;kube-apiserver-caasp-master-3-caasp-jobs-pr-test-pr-1362-0:Running;kube-apiserver-caasp-master-3-caasp-jobs-pr-test-pr-1362-1:Running;kube-apiserver-caasp-master-3-caasp-jobs-pr-test-pr-1362-2:Running;kube-controller-manager-caasp-master-3-caasp-jobs-pr-test-pr-1362-0:Running;kube-controller-manager-caasp-master-3-caasp-jobs-pr-test-pr-1362-1:Running;kube-controller-manager-caasp-master-3-caasp-jobs-pr-test-pr-1362-2:Running;kube-proxy-bkw9s:Running;kube-proxy-n4b5j:Running;kube-proxy-rnrjr:Running;kube-proxy-tjhkc:Running;kube-proxy-tzpxl:Running;kube-proxy-z22vs:Running;kube-scheduler-caasp-master-3-caasp-jobs-pr-test-pr-1362-0:Running;kube-scheduler-caasp-master-3-caasp-jobs-pr-test-pr-1362-1:Running;kube-scheduler-caasp-master-3-caasp-jobs-pr-test-pr-1362-2:Running;kucero-cg626:Running;kucero-q7lj5:Running;kucero-shp8h:Running;kured-49whv:Running;kured-6cltk:Running;kured-8xbrc:Running;kured-blssx:Running;kured-lqg9j:Running;kured-wv5x7:Running;metrics-server-7dc848f7b4-b6lbk:Running;metrics-server-7dc848f7b4-xg2b8:Running;oidc-dex-68d9f5b648-pkr5m:Running;oidc-dex-68d9f5b648-vqswc:Running;oidc-dex-68d9f5b648-w5zxl:Running;oidc-gangway-fc65d45-9lnlg:Running;oidc-gangway-fc65d45-qbkdm:Running;oidc-gangway-fc65d45-qzr8b:Running;
Exception condition "check system pods ready" not satisfied after 180 seconds executing command check-cluster
```

**Comment by jordimassaguerpla** [comment]
On the daily job, I see cilium-operator in Running state

https://ci.suse.de/view/CaaSP/view/v4.5%20Dashboard/job/caasp-jobs/job/e2e/job/v4.5/job/vmware/job/test_cilium-daily/122/consoleText

**Comment by jordimassaguerpla** [comment]
@mrostecki Something is not going well with this new envoy in the cilium-operator. Could you please check? You can run a cluster and keep it running with https://ci.suse.de/view/CaaSP/view/CaaSP-Dev/job/caasp-jobs/job/dev/job/e2e-test/build?delay=0sec .

Select the "RETAIN_CLUSTER"

at the REPO_BRANCH use the 4.5.1

and the E2E_MAKE_TARGET_NAME use test_cilium

**Comment by jordimassaguerpla** [comment]
@mmnelemane could you please put back the -rev3 so we know if we are pulling this image in the tests?

**Comment by mmnelemane** [comment]
> @mmnelemane could you please put back the -rev3 so we know if we are pulling this image in the tests?

@jordimassaguerpla Done. Thanks

**Review by jordimassaguerpla — CHANGES_REQUESTED** [review]
tests passed. However this is not for master. Please merge first the master branch and then this one.

**Comment by jordimassaguerpla** [comment]
Please do not merge until this code is in master branch

**Comment by mmnelemane** [comment]
> Please do not merge until this code is in master branch
https://github.com/SUSE/skuba/pull/1363 for `master` branch.

**Review by jordimassaguerpla — APPROVED** [review]

**Pull request merged**
