### PR TITLE
Update kured to 1.4.3

### PR DESCRIPTION
**Pull request by dirkmueller**
This version is declared as supporting k8s 1.18.x

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by evrardjp** [comment]
ofc we'll need to update the kured images too, to make it work.

**Comment by jordimassaguerpla** [comment]
@dirkmueller Something is failing. The kured containers are not in a running state. This is the error I see

kured-d7tz9:Pending;kured-rgqds:Pending;kured-vk5rz:Pending;kured-w8lcr:Pending;kured-wh9pt:Pending;kured-xc4xx:Pending

The tests:

https://ci.suse.de/blue/organizations/jenkins/caasp-jobs%2Fpr%2Ftest/detail/PR-1215/7/pipeline

Something may be wrong on the kured images.

Could you take a look?

Do you need help from us?

**Comment by evrardjp** [comment]
Retriggered tests, as this PR happened during a rebuild in devel:caasp. I think this should be able to merge, even if Devel:CaaSP:5 is lagging behind the latest changes from k8sProvides.

**Comment by evrardjp** [comment]
> @dirkmueller Something is failing. The kured containers are not in a running state. This is the error I see
> 
> kured-d7tz9:Pending;kured-rgqds:Pending;kured-vk5rz:Pending;kured-w8lcr:Pending;kured-wh9pt:Pending;kured-xc4xx:Pending
> 
> The tests:
> 
> https://ci.suse.de/blue/organizations/jenkins/caasp-jobs%2Fpr%2Ftest/detail/PR-1215/7/pipeline
> 
> Something may be wrong on the kured images.
> 
> Could you take a look?
> 
> Do you need help from us?

I had a look, it doesn't manage to pull the image:
```
Jul 07 13:57:53 0100164091233 crio[5637]: time="2020-07-07 13:57:53.379015205Z" level=info msg="Image registry.suse.de/devel/caasp/5/containers/containers/caasp/v5/kured:1.4.3 not found" id=296ffb3f-c5e0-49ef-93ce-37237156a173 name=/runtime.v1alpha2.ImageService/ImageStatus
```
I thought that when there is a branch it would be able to pull the containers from the branch? 
When I check on https://registry.suse.de , I only see (in the webinterface) devel/caasp/5/branches/kured-update/containers/caasp/v5/kured:1.4.3. How can I be sure if the mirroring was properly wired? Should we also cp the files in /etc/ for {kubernetes|crio}  as build artefacts?

**Comment by pablochacin** [comment]
@evrardjp  You can look at the crio configuration in the nodes. The files are collected as part of the platform logs.

**Comment by jordimassaguerpla** [comment]
This is the cri-o conf

unqualified-search-registries = [ "docker.io",]
[[registry]]
prefix = "registry.suse.de/devel/caasp/5/containers/cr/containers"
location = "registry.suse.de/devel/caasp/5/containers/cr/containers"
[[registry.mirror]]
location = "registry.suse.de/devel/caasp/5/branches/kured-update/containers"
insecure = true

**Comment by jordimassaguerpla** [comment]
I see registry.suse.de/devel/caasp/5/branches/kured-update/containers/caasp/v5/kured                                                                                1.4.3, 1.4.3-rev2, 1.4.3-rev2-build8.4, beta

**Comment by jordimassaguerpla** [comment]
@saschagrunert Could you give us some light here?

With this conf https://github.com/SUSE/skuba/pull/1215#issuecomment-655474312
when the test pulls 

registry.suse.de/devel/caasp/5/containers/containers/caasp/v5/kured:1.4.3

It says 

Image registry.suse.de/devel/caasp/5/containers/containers/caasp/v5/kured:1.4.3 not found (https://github.com/SUSE/skuba/pull/1215#issuecomment-655406947)

instead of pulling 

registry.suse.de/devel/caasp/5/branches/kured-update/containers/caasp/v5/kured:1.4.3

**Comment by jordimassaguerpla** [comment]
should the prefix and location be
registry.suse.de/devel/caasp/5/containers/containers
instead of
registry.suse.de/devel/caasp/5/containers/cr/containers
?

**Comment by pablochacin** [comment]
@jordimassaguerpla  seems to be using a mirror, because the PR has the `ci-repo` label

**Comment by jordimassaguerpla** [comment]
> @jordimassaguerpla seems to be using a mirror, because the PR has the `ci-repo` label. I think the message doesn't change because you are pulling the image from a mirror, but you still are naming it the same.

I see

I was wondering whether the configuration might be wrong , as we have the "CR" in the prefix but the image is not pulled from the CR

registry.suse.de/devel/caasp/5/containers/**cr**/containers
vs
registry.suse.de/devel/caasp/5/containers/containers/

**Comment by jordimassaguerpla** [comment]
I am rebasing this PR at https://github.com/SUSE/skuba/pull/1244 to get https://github.com/SUSE/skuba/pull/1239

**Comment by jordimassaguerpla** [comment]
The rebased PR worked
https://github.com/SUSE/skuba/pull/1244

**Pull request closed without merging**
