### PR TITLE
Add custom bootcmds to terraform

### PR DESCRIPTION
**Pull request by pablochacin**
## Why is this PR needed?
In some cases, it vould be convenient to execute commands when booting the cluster nodes, in order to adapt them to their environment. For example, mounting a remote volume. This requirement [appeared in the CI trying to solve issues with the etcd database](https://github.com/SUSE/avant-garde/issues/1118), and it may result conveniently in other cases.

Fixes https://github.com/SUSE/avant-garde/issues/1131

Required by https://github.com/SUSE/avant-garde/issues/1118

## What does this PR do?

Adds the variables `master_bootcmds` and `worker_bootcmds` which allow specifying a list of commands to be added to the `bootcmds` section of the cloud-init for the master and worker nodes, respectively. The variables are optional and if not specified, there's no change as perceived by the user. 

## Anything else a reviewer needs to know?

Testing this change requires supplying  `master_bootcmds` and/or `worker_bootcmds` in the `terraform.tfvars` or in the terraform command line.  The example below mounts a ramdisk to the workers to be used by etcd.

`terraform.tfvars`
```
   ...
   "master_bootcmds" : [
        "mkdir -p /var/lib/etcd",
        "mount -t tmpfs -o size=2048m tmpfs /var/lib/etcd"
   ]
```

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by kravciak** [comment]
what happens with /var/lib/etcd if you reboot a node?

**Comment by pablochacin** [comment]
> what happens with /var/lib/etcd if you reboot a node?

I haven't tried. But that's no the purpose of this PR. I prefer to discuss that in the PR that will introduce those changes.

**Comment by cmurphy** [comment]
The issue and the dependent PR were both closed so is this still needed?

**Comment by jordimassaguerpla** [comment]
Hi!
New code has been merged in master regarding terraform 0.12. Please rebase your branch to take this changes in.
Happy hacking

**Comment by pablochacin** [comment]
no longer needed.

**Pull request closed without merging**
