### PR TITLE
CI: Add log parser to pr jobs

### PR DESCRIPTION
**Pull request by Itxaka**
Enables the log parser[0] for pr jobs and provides a simple list
to filter out uneeded logs and highlights proper ones

[0] https://plugins.jenkins.io/log-parser/

## Why is this PR needed?

Does it fix an issue? addresses a business case?

add a description and link to the issue if one exists.

Fixes #

**Reminder**: Add the "fixes bsc#XXXX" to the title of the commit so that it will
appear in the changelog.

## What does this PR do?

please include a brief "management" technical overview (details are in the code)

## Anything else a reviewer needs to know?

Special test cases, manual steps, links to resources or anything else that could be helpful to the reviewer.

## Info for QA

This is info for QA so that they can validate this. This is **mandatory** if this PR fixes a bug.
If this is a new feature, a good description in "What does this PR do" may be enough.

### Related info

Info that can be relevant for QA:
* link to other PRs that should be merged together
* link to packages that should be released together
* upstream issues

### Status **BEFORE** applying the patch

How can we reproduce the issue? How can we see this issue? Please provide the steps and the prove
this issue is not fixed.

### Status **AFTER** applying the patch

How can we validate this issue is fixed? Please provide the steps and the prove this issue is fixed.

## Docs

If docs need to be updated, please add a link to a PR to https://github.com/SUSE/doc-caasp.
At the time of creating the issue, this PR can be work in progress (set its title to [WIP]),
but the documentation needs to be finalized before the PR can be merged. 

# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Comment by Itxaka** [comment]
yep @davidcassany its a separate thing altogether and would not touch the actual log. Doesnt seem to work though :D

**Comment by Itxaka** [comment]
Seems to work even if the job failed for an unrelated issue: https://ci.suse.de/job/caasp-jobs/job/v4/job/pr/job/test/view/change-requests/job/PR-996/5/parsed_console/

**Comment by pablochacin** [comment]
@Itxaka is this already an issue?
```
 NOTE: Some bad parsing rules have been found:
Bad parsing rule:ok /*Identity added*/, Error:Dangling meta character '*' near index 0<br/>*Identity added*<br/>^
``` 
https://ci.suse.de/job/caasp-jobs/job/v4/job/pr/job/test/view/change-requests/job/PR-996/5/parsed_console/

**Comment by Itxaka** [comment]
@pablochacin good catch! Its good to know that it will ignore bad rules instead of directly failing, let me have a look...

**Comment by Itxaka** [comment]
In any case, this seems useless because we are logging the skuba output as DEBUG at all times, which makes parsing difficult...we get a log of debug statements in the parser

**Comment by pablochacin** [comment]
@Itxaka yes, that's because we are reporting as `error` all that comes from `stderr`.

**Comment by Itxaka** [comment]
> @Itxaka yes, that's because we are reporting as error all that comes from stderr.

And that would be fine, but skuba seems to report everything as error, when it should be either info or debug:

```
2020-03-13 15:07:33 ERROR] I0313 15:07:33.333952   18565 ssh.go:193] The following 33 NEW packages are going to be installed:
I0313 15:07:33.333984   18565 ssh.go:193]   apparmor-abstractions apparmor-parser apparmor-profiles bash-completion caasp-config caasp-release cni cni-plugins conmon conntrack-tools cri-o cri-o-kubeadm-criconfig cri-tools ethtool kubernetes-client kubernetes-common kubernetes-kubeadm kubernetes-kubelet libcontainers-common libnetfilter_cthelper0 libnetfilter_cttimeout1 libnetfilter_queue1 libwrap0 lsof patterns-base-apparmor patterns-base-basesystem patterns-caasp-Node-1.16 runc skuba-update socat supportutils supportutils-plugin-suse-caasp sysfsutils

2020-03-13 15:07:33 ERROR] I0313 15:07:33.333984   18565 ssh.go:193]   apparmor-abstractions apparmor-parser apparmor-profiles bash-completion caasp-config caasp-release cni cni-plugins conmon conntrack-tools cri-o cri-o-kubeadm-criconfig cri-tools ethtool kubernetes-client kubernetes-common kubernetes-kubeadm kubernetes-kubelet libcontainers-common libnetfilter_cthelper0 libnetfilter_cttimeout1 libnetfilter_queue1 libwrap0 lsof patterns-base-apparmor patterns-base-basesystem patterns-caasp-Node-1.16 runc skuba-update socat supportutils supportutils-plugin-suse-caasp sysfsutils
I0313 15:07:33.334032   18565 ssh.go:193]```

**Comment by pablochacin** [comment]
> And that would be fine, but skuba seems to report everything as error, when it should be either info or debug:

I'm not sure who is putting that `ERROR` label I think it is `testrunner` when logging output from `stderr`. I discussed this with @ereslibre time ago and certainly, debugging information is supposed to go to `stderr` as per Linux conventions  -- what makes a lot of sense if you want to trace the execution of a command without polluting the stdout, which may be piped to another command.

**Comment by Itxaka** [comment]
@pablochacin @ereslibre While looking up the stderr stuff to see if there was an alternative I stumbled upon [this](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap01.html#tag_17_04)

```
Default Behavior: When this section is listed as "The standard error shall be used only for diagnostic messages.", it means that, unless otherwise stated, the diagnostic messages shall be sent to the standard error only when the exit status indicates that an error occurred and the utility is used as described by this volume of POSIX.1-2008.
```

So this seems to indicate that diagnostic (which I think this is, as its only visible when verbose) should be sent to stderr **when** there is an error, which makes sense as to not pollute the stderr, which another utility could be reading for failures.

I still think this is wrong and we are mixing stuff. Stderr should be for errors when they occur, otherwise log files, normal output, `silent` flags are the way to go.

**Comment by ereslibre** [comment]
@Itxaka, from that documentation and your quote:

If the STDERR section contains `The standard error shall be used only for diagnostic messages`, then it is expected that the standard error will only contain diagnostic messages when the exit status is not 0. E.g, on the `man qmsg` manual.

In general, you are free to use these streams as you best consider. If your programs can be heavily piped and they are very chatty, I think it's reasonable to just print the "pipable" content to `stdout`, and print some things on `stderr`. Think about `curl` for example. It will print the contents to `stdout`, but progress on `stderr`.

**Comment by pablochacin** [comment]
@Itxaka To add more context to the conversation and possible alternatives: originally `testrunner` logged the `stderr` as `ERROR` only if the command it had invoked failed (remember this happens in the `run_shellcmd` routine in `utils` class). This, however, caused some issues. Some commands did not properly report errors (IIRC, `kubectl`). Besides, as we moved to a model on which we logged the output as it was produced instead of at the end of the execution, we can't relly on the command's return code to decide how to log the output coming from  `stderr`

There was some conversation about all this and we decided to follow a simple approach: all `stderr` as ERROR.

**Comment by Itxaka** [comment]
Thanks for the feedback @pablochacin @ereslibre 

In this context Im wondering if its even worth using the parsing then, because we are doing extra job and we are gonna get a lot of false positives (not really but all the output is gonna be tagged as ERROR) so Im not sure if this is gonna be helpful :/

**Pull request closed without merging**
