### PR TITLE
Update to k8s 1.18.8 api version

### PR DESCRIPTION
**Pull request by dirkmueller**
## Why is this PR needed?

also includes a bump of crypto and json library versions to bugfixed/security fixed versions.

Fixes https://github.com/SUSE/avant-garde/issues/1907
# Merge restrictions

(Please do not edit this)

We are in *v4-maintenance phase*, so we will restrict what can be merged to prevent unexpected surprises:

    What can be merged (merge criteria):
        2 approvals:
            1 developer: code is fine
            1 QA: QA is fine
        there is a PR for updating documentation (or a statement that this is not needed)

### CODE REVIEW

**Review by Klaven — DISMISSED** [review]
/lgtm

**Comment by jordimassaguerpla** [comment]
@dirkmueller Do you have the issue number or bsc for this? If there is none, could you create one? We need it for planning the releases. Thanks.

**Review by chentex — APPROVED** [review]
LGTM

**Comment by dirkmueller** [comment]
> @dirkmueller Do you have the issue number or bsc for this? If there is none, could you create one? We need it for planning the releases. Thanks.

not specifically, but I consider it part of https://github.com/SUSE/avant-garde/issues/1907 . it is more a tech debt cleanup than anything else. we shouldn't hardcode outdated dependencies, even in a "shift left" paradigm.

**Comment by chentex** [comment]
We have merged this PR https://github.com/SUSE/skuba/pull/1413 that already covers the version, I will close this PR.

**Pull request closed without merging**
